=== Krutarth1997/Test_Validation/door_1.1/files/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "comments": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "version": {
            "type": "number"
        },
        "simulation_parameters": {
            "type": "object",
            "properties": {
                "fps": {
                    "type": "number"
                },
                "time_step": {
                    "type": "number"
                },
                "number_agents": {
                    "type": "number"
                },
                "simulation_time": {
                    "type": "number"
                }
            },
            "required": ["fps", "time_step", "number_agents", "simulation_time"]
        },
        "motivation_parameters": {
            "type": "object",
            "properties": {
                "normal_v_0": {
                    "type": "number"
                },
                "normal_time_gap": {
                    "type": "number"
                }
            },
            "motivation_doors": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "label": {
                            "type": "string"
                        },
                        "vertices": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "number"
                                },
                                "minItems": 2,
                                "maxItems": 2
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    },
                    "required": ["id", "vertices", "label"]
                },
                "minItems": 1,
                "maxItems": 1
            },
            "required": ["normal_v_0", "normal_time_gap", "motivation_doors"]
        },
        "grid_parameters": {
            "type": "object",
            "properties": {
                "min_v_0": {
                    "type": "number"
                },
                "max_v_0": {
                    "type": "number"
                },
                "v_0_step": {
                    "type": "number"
                },
                "min_time_gap": {
                    "type": "number"
                },
                "max_time_gap": {
                    "type": "number"
                },
                "time_gap_step": {
                    "type": "number"
                }
            },
            "required": ["min_v_0", "max_v_0", "v_0_step", "min_time_gap", "max_time_gap", "time_gap_step"]
        },
        "accessible_areas": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices"]
            }
        },
        "destinations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "label": {
                        "type": "string"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices", "label"]
            }
        },   
        "velocity_model_parameter_profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "time_gap": {
                        "type": "number"
                    },
                    "tau": {
                        "type": "number"
                    },
                    "v0": {
                        "type": "number"
                    },
                    "radius": {
                        "type": "number"
                    }
                },
                "required": ["id", "time_gap", "tau", "v0", "radius"]
            }
        },
        "way_points": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "coordinates": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "distance": {
                        "type": "number"
                    }
                },
                "required": ["coordinates", "distance"]
            }
        },
        "distribution_polygons": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "vertices": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            },
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                },
                "required": ["id", "vertices"]
            }
        }
    },
    "required": ["version", "simulation_parameters", "accessible_areas", "destinations", "velocity_model_parameter_profiles", "way_points", "distribution_polygons"]
}

=== Krutarth1997/Test_Validation/door_0.9/files/bottleneck.json
{
    "comments": [
        "This file includes all important information",
        "to start a jupedsim simulation with the motivation model"
    ],
    "version": 0.1,
    "simulation_parameters": {
        "fps": 10,
        "time_step": 0.01,
        "number_agents": 60,
        "simulation_time": 100
    },
    "motivation_parameters": {
        "active": 0,
        "normal_v_0": 1.01,
        "normal_time_gap": 0.7,
        "motivation_doors": [
            {
                "id": 1,
                "label": "door",
                "vertices": [
                    [
                        60,
                        101.55
                    ],
                    [
                        60,
                        102.45
                    ]
                ]
            }
        ]
    },
    "grid_parameters": {
        "min_v_0": 1,
        "max_v_0": 2,
        "v_0_step": 0.1,
        "min_time_gap": 0.1,
        "max_time_gap": 1,
        "time_gap_step": 0.1
    },
    "accessible_areas": [
        {
            "id": 1,
            "vertices": [
                [
                    50.0,
                    100.0
                ],
                [
                    60.0,
                    100.0
                ],
                [
                    60.0,
                    104.0
                ],
                [
                    50.0,
                    104.0
                ]
            ]
        },
        {
            "id": 2,
            "vertices": [
                [
                    60.0,
                    101.55
                ],
                [
                    62.0,
                    101.55
                ],
                [
                    62.0,
                    102.45
                ],
                [
                    60.0,
                    102.45
                ]
            ]
        },
        {
            "id": 3,
            "vertices": [
                [
                    62.0,
                    100.0
                ],
                [
                    64.0,
                    100.0
                ],
                [
                    64.0,
                    104.0
                ],
                [
                    62.0,
                    104.0
                ]
            ]
        }
    ],
    "destinations": [
        {
            "id": 1,
            "label": "exit",
            "vertices": [
                [
                    63.5,
                    102.6
                ],
                [
                    63.5,
                    101.4
                ],
                [
                    64,
                    101.4
                ],
                [
                    64,
                    102.6
                ]
            ]
        }
    ],
    "velocity_model_parameter_profiles": [
        {
            "id": 1,
            "time_gap": 1.0,
            "tau": 0.5,
            "v0": 1.0,
            "radius": 0.15
        },
        {
            "id": 2,
            "time_gap": 1.0,
            "tau": 0.5,
            "v0": 0.1,
            "radius": 0.2
        }
    ],
    "way_points": [
        {
            "coordinates": [
                61.0,
                102.0
            ],
            "distance": 1
        },
        {
            "coordinates": [
                63.75,
                102.0
            ],
            "distance": 0.4
        }
    ],
    "distribution_polygons": [
        {
            "id": 1,
            "vertices": [
                [
                    50.0,
                    100.0
                ],
                [
                    56.0,
                    100.0
                ],
                [
                    56.0,
                    104.0
                ],
                [
                    50.0,
                    104.0
                ]
            ]
        },
        {
            "id": 2,
            "vertices": [
                [
                    56.5,
                    100.0
                ],
                [
                    60.0,
                    100.0
                ],
                [
                    60.0,
                    104.0
                ],
                [
                    56.5,
                    104.0
                ]
            ]
        }
    ]
}
